Sprint3/step1
Barresi/yandex-burger pull request #5
Opened 2023-07-21 10:28 UTC by Barresi

2023-07-21 12:30 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/KuzsS8ylLJTZSg>;

- При перезагрузке страницы на странице профиля, авторизованный пользователь не должен попадать на главную страницу;

- По чек-листу, требуется реализовать:

  - Вам нужно проверить запросы, некоторые их них (`POST /auth/user`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

- Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку;

- Если значения нет, то нужно использовать null, а не пустой объект.

- Поменяйте расширение файлов у стора и других файлов. Там где нет `jsx`, должно быть расширение `.js`, а не `.jsx`;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-07-21 12:30 UTC, ArslanMustafin commented on src/components/modal/modal-content/modal-ingredient-details/modal-ingredient-details.jsx
> +     const [ingredientInfo, setIngredientInfo] = useState({});
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/utils/api.jsx
> +     const response = await fetch(`${URL}/auth/user`, {
**Надо исправить:**

Тут нужно использовать fetchWithRefresh

2023-07-21 12:30 UTC, ArslanMustafin commented on src/utils/api.jsx
> +     };
**Надо исправить:**

Здесь и далее. Там, где вы передаёте токен в запрос.

Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};

// использование

export const postIngredients = arrayIngredients => {
  return fetchWithRefresh(`${URL}/orders`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json;charset=utf-8',
      authorization: getCookie('token'),
    },
    body: JSON.stringify({
      ingredients: data,
    }),
  }).then(data => {
    if (data?.success) return data;
    return Promise.reject(data);
  });
};
```

Лучше сделать универсальную функцию для запросов.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/utils/api.jsx
> +     const response = await fetch(`${URL}/orders`, {
**Надо исправить:**

Тут нужно использовать fetchWithRefresh

2023-07-21 12:30 UTC, ArslanMustafin commented on src/components/protected-route-element/protected-route-element.jsx
> +};
**Надо исправить:**

Оптимальный пример компонента ProtectRoute:

```js
export const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

// использование

<Route
  path="/register"
  element={
    <ProtectedRoute onlyUnAuth={true}>
      <Register />
    </ProtectedRoute>
  }
/>

<Route
  path="/profile"
  element={
    <ProtectedRoute>
      <Profile />
    </ProtectedRoute>
  }
/>
```

Вам не хватает вот этой проверки, поэтому у вас при перезагрузке страницы авторизованный пользователь попадает на главную страницу.

```js
if (!isAuthChecked) {
  return <Preloader />;
}
```

`isAuthChecked` - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет `true` (не зависит от результат, т.к. он будет `true` в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет `false`.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +     const refreshToken = getCookie('refreshToken');
**Надо исправить:**

получать токены нужно в момент запроса. Делаете это там где вы используете fetch.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +     }, [accessToken, refreshToken]);
**Надо исправить:**

лучше переименовать функцию в `getUser` и перенести её в след. useEffect (там где вы делаете запрос ингредиентов).

2023-07-21 12:30 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +          if (isUserLoaded) {
**Надо исправить:**

Тут вы должны проверять есть ли у пользователя токен, если нет, то нужно перенаправлять его на авторизацию.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/forgot-password/forgot-password.jsx
> +     }
**Надо исправить:**

тут не должно быть проверок на пользователя, все проверки должны быть в `ProtectRoute` компоненте.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/forgot-password/forgot-password.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={checkEmail}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/login/login.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={sendData}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/login/login.jsx
> +     }
**Надо исправить:**

тут не должно быть проверок на пользователя, все проверки должны быть в `ProtectRoute` компоненте.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/profile/pages/edit-profile-info/edit-profile-info.jsx
> +                         <Button htmlType='button' type='primary' size='medium' onClick={editProfile}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/register/register.jsx
> +     }
**Надо исправить:**

тут не должно быть проверок на пользователя, все проверки должны быть в `ProtectRoute` компоненте.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/register/register.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={sendData}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/reset-password/reset-password.jsx
> +     if (isUserLoaded || !state) {
**Надо исправить:**

тут не должно быть проверки на пользователя `isUserLoaded`, все проверки должны быть в `ProtectRoute` компоненте.

2023-07-21 12:30 UTC, ArslanMustafin commented on src/pages/reset-password/reset-password.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={changePassword}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-07-21 14:30 UTC, Barresi commented on src/components/modal/modal-content/modal-ingredient-details/modal-ingredient-details.jsx
> +     const [ingredientInfo, setIngredientInfo] = useState({});
Исправил

2023-07-21 15:42 UTC, Barresi commented on src/utils/api.jsx
> +     const response = await fetch(`${URL}/auth/user`, {
Исправил

2023-07-21 15:42 UTC, Barresi commented on src/utils/api.jsx
> +     };
Исправил

2023-07-21 15:42 UTC, Barresi commented on src/utils/api.jsx
> +     const response = await fetch(`${URL}/orders`, {
Исправил

2023-07-21 15:52 UTC, Barresi commented on src/components/app/app.jsx
> +     const refreshToken = getCookie('refreshToken');
Исправил

2023-07-21 15:54 UTC, Barresi commented on src/components/app/app.jsx
> +     }, [accessToken, refreshToken]);
Исправил

2023-07-21 17:31 UTC, Barresi commented on src/components/burger-constructor/burger-constructor.jsx
> +          if (isUserLoaded) {
За авторизацию пользователя у меня отвечает именно переменная isUserLoaded. Если пользователь не авторизован - переменная isUserLoaded будет в значении false

2023-07-21 18:04 UTC, Barresi commented on src/components/protected-route-element/protected-route-element.jsx
> +};
Исправил

2023-07-21 18:06 UTC, Barresi commented on src/pages/forgot-password/forgot-password.jsx
> +     }
Исправил

2023-07-21 18:06 UTC, Barresi commented on src/pages/login/login.jsx
> +     }
Исправил

2023-07-21 18:07 UTC, Barresi commented on src/pages/register/register.jsx
> +     }
Исправил

2023-07-21 18:10 UTC, Barresi commented on src/pages/reset-password/reset-password.jsx
> +     if (isUserLoaded || !state) {
Исправил

2023-07-21 18:22 UTC, Barresi commented on src/pages/login/login.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={sendData}>
Исправил

2023-07-21 18:44 UTC, Barresi commented on src/pages/register/register.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={sendData}>
Исправил

2023-07-21 18:57 UTC, Barresi commented on src/pages/reset-password/reset-password.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={changePassword}>
Исправил

2023-07-21 18:57 UTC, Barresi commented on src/pages/forgot-password/forgot-password.jsx
> +                    <Button htmlType='button' type='primary' size='medium' extraClass='mb-20' onClick={checkEmail}>
Исправил

2023-07-21 19:09 UTC, Barresi commented on src/pages/profile/pages/edit-profile-info/edit-profile-info.jsx
> +                         <Button htmlType='button' type='primary' size='medium' onClick={editProfile}>
Исправил

2023-07-22 14:41 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +     /* eslint-enable */
**Можно лучше:**

Тут лучше вот так написать, постарайтесь по минимум (1 строке) отключать линтер.

```js
useEffect(() => {
  dispatch(getDataIngredients());
  getUser();
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, []);
```

2023-07-22 14:41 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +          if (isUserLoaded) {
В таком случае стоит переименовать это поле например в `isUserAuth`, чтобы было понятно за что оно отвечает. Но оптимальный вариант избавиться от этого поля вообще, т.к. оно избыточно. У нас достаточно параметров (токены, сам объект пользователя (если будете использовать его, то изначально поле `user` должно быть `null`, а не объектом),) для того чтобы определить есть пользователь в системе или нет. Самый оптимальный вариант это использовать проверку на токен.

2023-07-22 14:50 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +     // if add function getUser in deps, happened some bugs xD
**Можно лучше:**

Ну ожидаемо что при каждом рендере функции будут создаваться заново. Есть 2 варианта исправления: 
1. использовать `useCallback`, но это плохой вариант с точки зрения оптимизации.
2. просто использовать тут сразу `dispatch(getUserInfo())`, без всяких других доп. функций - это оптимальный вариант, тем более у вас не так часто используются эти экшены.

2023-07-22 14:50 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-22 15:10 UTC, Barresi commented on src/components/app/app.jsx
> +     // if add function getUser in deps, happened some bugs xD
Исправил

2023-07-22 15:40 UTC, merged